// <auto-generated />
namespace PmaPlus.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class clubs_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(clubs_model));
        
        string IMigrationMetadata.Id
        {
            get { return "201504211041346_clubs_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
