// <auto-generated />
namespace PmaPlus.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class session_objective : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(session_objective));
        
        string IMigrationMetadata.Id
        {
            get { return "201507080910088_session_objective"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
