// <auto-generated />
namespace PmaPlus.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class user_createAt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_createAt));
        
        string IMigrationMetadata.Id
        {
            get { return "201504170839246_user_createAt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
