// <auto-generated />
namespace PmaPlus.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dashboards : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dashboards));
        
        string IMigrationMetadata.Id
        {
            get { return "201504170711053_dashboards"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
